issue/1-1
terehov-ar/10k_hours_tracking pull request #2
Opened 2022-01-03 12:32 UTC by terehov-ar

2022-01-03 13:19 UTC, SoundAsleep192 requested changes

2022-01-03 13:19 UTC, SoundAsleep192 commented on index.html
> +    <p style="text-align:left"><button>Add</button></p>
Please try to avoid inline-styles, consider creating a css class for this even if it contains only one property

2022-01-03 13:19 UTC, SoundAsleep192 commented on index.html
> +    <p><textarea rows="3" cols="35" name="textInsert">Your text</textarea></p>
the `<p>` around `<textarea>` is not needed

2022-01-03 13:19 UTC, SoundAsleep192 commented on index.html
> +        <p>...</p>
Please consider using the `<ul>` and `<li>` tags for a list instead of `<p>`

2022-01-03 18:01 UTC, terehov-ar reviewed
Fix all problems

2022-01-05 15:52 UTC, SoundAsleep192 commented
Good job! Now please change the commit names to follow the `conventional commits` spec ( https://www.conventionalcommits.org/en/about/ )
For doing that you can use `git rebase` in interactive mode

2022-01-08 15:17 UTC, SoundAsleep192 approved these changes

2022-01-08 15:32 UTC, merged